### ISSUE TITLE
虫师，wait和find写反了吧

### ISSUE THREAD

**Issue by liang1vs1** [defnngj/selenium_page_objects#1]
def wait(self, context):
        try:
            return context.find_element(*self.locator)
        except NoSuchElementException:
            return None

    def find(self, context):
        for i in range(self.time_out):
            if self.wait(context) is not None:
                return self.wait(context)
            else:
                sleep(1)
        else:
            return None

**Comment by defnngj** [comment]
```wait()``` 和 ```find()`` 为内部方法，在命名上欠妥，```wait()``` 改为 ```get_element()```较为合适，不过，这并不影响使用。
